stages:
  - install
  - test
  - push
  - deploy

cache:
  untracked: true
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .npm/
    - cache/Cypress

variables:
  NPM_TOKEN: $NPM_TOKEN
  GITHUB_TOKEN: $GITHUB_TOKEN
  GITLAB_TOKEN: $GITLAB_TOKEN

install:
  image: node:16.10.0
  stage: install
  script:
    - npm install --prefer-offline --no-audit --cache --legacy-peer-deps .npm

test:
  image: node:16.10.0
  stage: test
  script:
    - npm install --prefer-offline --no-audit --cache --legacy-peer-deps .npm
    - npm test

push:npm:
  image: node:16.10.0
  stage: push
  script:
    - npm install --prefer-offline --no-audit --cache --legacy-peer-deps .npm
    - export NODE_OPTIONS="--max-old-space-size=8192" && npm run publish
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - project_url=$(echo $CI_PROJECT_URL | sed 's/https:\/\///')
    - git add libs
    - git commit -m "build npm publish [skip ci]"
    - git remote add smart "https://oauth2:$GITLAB_TOKEN@gitlab.smartsoft.biz.pl/core/framework"
    - git push smart HEAD:$CI_COMMIT_BRANCH -o ci.skip
    - git remote add github "https://oauth2:$GITHUB_TOKEN@github.com/emiljuchnikowski/smartsoft"
    - git push github HEAD:$CI_COMMIT_BRANCH
  dependencies:
    - install