FROM node:14-alpine
ENV NODE_ENV=production
WORKDIR /home/node/app

# Install deps for production only
COPY ./package* ./
RUN npm install && \
    npm cache clean --force
# Copy builded source from the upper builder stage
COPY dist/apps/api/crud .

# Expose ports (for orchestrators and dynamic reverse proxies)
EXPOSE 3334

# Start the app
CMD node main.js
