FROM node:16-alpine
ENV NODE_ENV=production
WORKDIR /home/node/app

COPY ./package* ./
RUN npm install --legacy-peer-deps && \
    npm cache clean --force

COPY dist/apps/api/files /home/node/app

EXPOSE 3334

# Start the app
CMD node main.js
