name: Push

# Controls when the action will run. 
on:
  push:
    branches: master

jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: actions/setup-node@v3
        run: npm install --prefer-offline --no-audit --legacy-peer-deps
        with:
          node-version: '16.10.0'
      - name: Test
        uses: actions/setup-node@v3
        run: npm test
        with:
          node-version: '16.10.0'
#      - name: Push NPM
#        image: node:16.10.0
#        run: export NODE_OPTIONS="--max-old-space-size=8192" && npm run publish
#      - name: Push GIT
#        usage: stefanzweifel/git-auto-commit-action@v4
#        run: export NODE_OPTIONS="--max-old-space-size=8192" && npm run publish
