name: Push

on:
  push:
    branches: master

jobs:
  build:
    name: Build
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        continue-on-error: true
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
        run: |
              echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> npmrc.config
      - name: Commit
        continue-on-error: true
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "build(github): npm publish [skip ci]"
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'
      - name: Install
        run: npm i --prefer-offline --no-audit
      - name: Test
        run: npm test
      - name: Publish
        continue-on-error: true
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
        run: |
              echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
              npm run publish
      - name: Commit
        continue-on-error: true
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "build(github): npm publish [skip ci]"
